"""Cross-validation of Bai-Perron against R strucchange reference values.

This module tests the Python ``BaiPerronTest`` implementation against
reference values produced by R's ``strucchange::breakpoints()``.  The
reference datasets (CSV) and the R script that generated them live in
``tests/reference_data/``.

To regenerate reference values:
    Rscript tests/reference_data/generate_bai_perron_reference.R

References
----------
Bai, J., & Perron, P. (2003). Computation and analysis of multiple
    structural change models. *J. Applied Econometrics*, 18(1), 1-22.

Zeileis, A., Leisch, F., Hornik, K., & Kleiber, C. (2002). strucchange:
    An R Package for Testing for Structural Change in Linear Regression
    Models. *J. Statistical Software*, 7(2), 1-38.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from regimes import BaiPerronTest

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
_REF_DIR = Path(__file__).resolve().parent.parent / "reference_data"


def _load_csv(name: str) -> dict[str, np.ndarray]:
    """Load a reference CSV produced by the R script."""
    path = _REF_DIR / name
    if not path.exists():
        pytest.skip(f"Reference dataset not found: {path}")
    import csv

    with open(path) as f:
        reader = csv.DictReader(f)
        rows = list(reader)
    result: dict[str, np.ndarray] = {}
    for key in rows[0]:
        result[key] = np.array([float(row[key]) for row in rows])
    return result


# ===================================================================
# Reference values from R strucchange (generated by the R script)
# ===================================================================

# DGP 1: Mean shift, y ~ 1, n=200, true break at t=100
_DGP1_R_BREAKS = [100]
_DGP1_R_RSS = {
    0: 479.2535813115,
    1: 47.0733641609,
    2: 46.6828086623,
    3: 46.4338997888,
}

# DGP 2: Regression break, y ~ x, n=200, true break at t=100
_DGP2_R_BREAKS = [100]
_DGP2_R_RSS = {
    0: 253.6054598961,
    1: 17.5010895678,
    2: 17.0368412332,
    3: 16.6144328427,
}

# DGP 3: Two mean shifts, y ~ 1, n=240, true breaks at t=80,160
_DGP3_R_BREAKS = [80, 160]
_DGP3_R_RSS = {
    0: 419.1984256890,
    1: 220.6889051735,
    2: 53.6841676190,
    3: 53.0953596959,
    4: 52.8421055475,
}


# ===================================================================
# Tests
# ===================================================================


class TestBaiPerronAgainstStrucchange:
    """Validate Python Bai-Perron against R strucchange reference values."""

    # ── DGP 1: simple mean shift ──────────────────────────────────

    def test_dgp1_break_location(self) -> None:
        """Break location for simple mean shift matches R."""
        data = _load_csv("dgp1_mean_shift.csv")
        y = data["y"]
        test = BaiPerronTest(y)
        result = test.fit(max_breaks=3, trimming=0.15, selection="bic")

        assert result.n_breaks == 1, (
            f"Expected 1 break (as R), got {result.n_breaks}"
        )
        assert list(result.break_indices) == _DGP1_R_BREAKS

    def test_dgp1_ssr_values(self) -> None:
        """SSR values for mean shift model match R within tolerance."""
        data = _load_csv("dgp1_mean_shift.csv")
        y = data["y"]
        test = BaiPerronTest(y)
        result = test.fit(max_breaks=3, trimming=0.15, selection="bic")

        for m, r_ssr in _DGP1_R_RSS.items():
            py_ssr = result.ssr[m]
            np.testing.assert_allclose(
                py_ssr,
                r_ssr,
                rtol=1e-6,
                err_msg=f"DGP1 SSR mismatch for m={m}: Python={py_ssr}, R={r_ssr}",
            )

    def test_dgp1_bic_selects_one_break(self) -> None:
        """BIC selects 1 break, same as R."""
        data = _load_csv("dgp1_mean_shift.csv")
        y = data["y"]
        test = BaiPerronTest(y)
        result = test.fit(max_breaks=3, trimming=0.15, selection="bic")
        assert result.n_breaks == 1

    # ── DGP 2: regression with all-breaking regressors ────────────

    def test_dgp2_break_location(self) -> None:
        """Break location for regression break matches R."""
        data = _load_csv("dgp2_regression_break.csv")
        y = data["y"]
        x = data["x"]

        # R does y ~ x which includes intercept + x, all breaking
        exog_break = np.column_stack([np.ones_like(y), x])
        test = BaiPerronTest(y, exog_break=exog_break)
        result = test.fit(max_breaks=3, trimming=0.15, selection="bic")

        assert result.n_breaks == 1, (
            f"Expected 1 break (as R), got {result.n_breaks}"
        )
        assert list(result.break_indices) == _DGP2_R_BREAKS

    def test_dgp2_ssr_values(self) -> None:
        """SSR values for regression break match R within tolerance."""
        data = _load_csv("dgp2_regression_break.csv")
        y = data["y"]
        x = data["x"]

        exog_break = np.column_stack([np.ones_like(y), x])
        test = BaiPerronTest(y, exog_break=exog_break)
        result = test.fit(max_breaks=3, trimming=0.15, selection="bic")

        for m, r_ssr in _DGP2_R_RSS.items():
            py_ssr = result.ssr[m]
            np.testing.assert_allclose(
                py_ssr,
                r_ssr,
                rtol=1e-6,
                err_msg=f"DGP2 SSR mismatch for m={m}: Python={py_ssr}, R={r_ssr}",
            )

    def test_dgp2_bic_selects_one_break(self) -> None:
        """BIC selects 1 break for regression break DGP, same as R."""
        data = _load_csv("dgp2_regression_break.csv")
        y = data["y"]
        x = data["x"]
        exog_break = np.column_stack([np.ones_like(y), x])
        test = BaiPerronTest(y, exog_break=exog_break)
        result = test.fit(max_breaks=3, trimming=0.15, selection="bic")
        assert result.n_breaks == 1

    # ── DGP 3: two mean shifts ────────────────────────────────────

    def test_dgp3_break_locations(self) -> None:
        """Break locations for two mean shifts match R."""
        data = _load_csv("dgp3_two_breaks.csv")
        y = data["y"]
        test = BaiPerronTest(y)
        result = test.fit(max_breaks=4, trimming=0.15, selection="bic")

        assert result.n_breaks == 2, (
            f"Expected 2 breaks (as R), got {result.n_breaks}"
        )
        assert list(result.break_indices) == _DGP3_R_BREAKS

    def test_dgp3_ssr_values(self) -> None:
        """SSR values for two-break model match R within tolerance."""
        data = _load_csv("dgp3_two_breaks.csv")
        y = data["y"]
        test = BaiPerronTest(y)
        result = test.fit(max_breaks=4, trimming=0.15, selection="bic")

        for m, r_ssr in _DGP3_R_RSS.items():
            py_ssr = result.ssr[m]
            np.testing.assert_allclose(
                py_ssr,
                r_ssr,
                rtol=1e-6,
                err_msg=f"DGP3 SSR mismatch for m={m}: Python={py_ssr}, R={r_ssr}",
            )

    def test_dgp3_bic_selects_two_breaks(self) -> None:
        """BIC selects 2 breaks for two-break DGP, same as R."""
        data = _load_csv("dgp3_two_breaks.csv")
        y = data["y"]
        test = BaiPerronTest(y)
        result = test.fit(max_breaks=4, trimming=0.15, selection="bic")
        assert result.n_breaks == 2

    # ── Aggregate: all DGPs detect correct number of breaks ───────

    def test_all_dgps_correct_selection(self) -> None:
        """All DGPs select the correct number of breaks via BIC."""
        cases = [
            ("dgp1_mean_shift.csv", None, 3, 1),
            ("dgp3_two_breaks.csv", None, 4, 2),
        ]
        for csv_name, _, max_b, expected_n in cases:
            data = _load_csv(csv_name)
            y = data["y"]
            test = BaiPerronTest(y)
            result = test.fit(max_breaks=max_b, trimming=0.15, selection="bic")
            assert result.n_breaks == expected_n, (
                f"{csv_name}: expected {expected_n} breaks, got {result.n_breaks}"
            )

        # DGP 2 with explicit exog_break
        data2 = _load_csv("dgp2_regression_break.csv")
        exog_break = np.column_stack([np.ones(len(data2["y"])), data2["x"]])
        test2 = BaiPerronTest(data2["y"], exog_break=exog_break)
        result2 = test2.fit(max_breaks=3, trimming=0.15, selection="bic")
        assert result2.n_breaks == 1
